[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*-json.log
    Tag               docker.*
    multiline.parser  docker, cri
    Mem_Buf_Limit     20MB
    Skip_Long_Lines   On
    Refresh_Interval  5

[FILTER]
    Name         parser
    Match        docker.*
    Key_Name     log
    Parser       json
    Reserve_Data On

[FILTER]
    Name   modify
    Match  docker.*
    Add    service backend
    Add    env production

[OUTPUT]
    Name            es
    Match           docker.*
    Host            elasticsearch
    Port            9200
    Logstash_Format On
    Logstash_Prefix backend-logs
    Logstash_DateFormat %Y.%m.%d
    Generate_ID     On
    Suppress_Type_Name On
