export default function FooterSection() {
  return (
    <div className="text-center pt-8 border-t border-gray-200 text-sm text-gray-500">
      <p>
        This report was generated by InternHub - Internship Management System
      </p>
      <p className="mt-1">© 2025 InternHub. All rights reserved.</p>
    </div>
  );
}
