name: Output Environment
description: Output shared environment variables (AWS region, ECR repository)

outputs:
  region:
    description: AWS region
    value: ${{ steps.output-env.outputs.region }}
  ecr-repository:
    description: ECR repository
    value: ${{ steps.output-env.outputs.ecr-repository }}

runs:
  using: composite
  steps:
    - name: Output environment variables
      id: output-env
      shell: bash
      env:
        AWS_REGION: us-east-1
        ECR_REPOSITORY: ecr-global-api
      run: |
        echo "region=${AWS_REGION}" >> "$GITHUB_OUTPUT"
        echo "ecr-repository=${ECR_REPOSITORY}" >> "$GITHUB_OUTPUT"
